### ISSUE TITLE
Compilation and C99

### ISSUE THREAD

**Issue by HanXHX** [ilyash/ngs#1]
Hi,

I can't compile on Ubuntu 14.04.4 LTS.

```
$ make --version
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for x86_64-pc-linux-gnu
$ gcc --version
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.1) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Compiling:
```
$ make
gcc -c -Wall -Wextra -gdwarf-4 -g3 -g -O1 obj.c -o obj.o
obj.c: In function ‘_encode_json_kern’:
obj.c:833:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for(unsigned int i=0; i<OBJ_LEN(obj); i++) {
   ^
obj.c:833:3: note: use option -std=c99 or -std=gnu99 to compile your code
make: *** [obj.o] Erreur 1
```

I tried to add `-std=c99` or `-std=gnu99` in Makefile (CFLAGS). But it doesn't work.

Cheers!

HanXHX

**Comment by ilyash** [comment]
I will take a look at it a bit later. Meanwhile can you try to compile using clang maybe? I'm using Debian Stretch and only test on it for now.

**Comment by ilyash** [comment]
Please try now. I haven't set up Ubuntu env yet so I can't confirm...

**Comment by ilyash** [comment]
Now compiles on Ubuntu 14.04. Fixed the documentation regarding the compilation. Please note the `gawk` dependency.

Either `git fetch; make clean` first or do a fresh checkout. Follow the documentation. I have successfully run the tests.
